### ISSUE TITLE
"cf scale" to use the same "X of Y instances running" UX as "cf push" and "cf restart" use

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-attic/cf#43]
I like the following UX for showing VMs booting up, and think it'd look good on `cf scale` too:

```
    1 of 500 instances running (1 running, 499 starting)
    9 of 500 instances running (9 running, 491 starting)
   21 of 500 instances running (21 running, 479 starting)
  142 of 500 instances running (142 running, 358 starting)
  225 of 500 instances running (225 running, 275 starting)
  305 of 500 instances running (305 running, 195 starting)
  378 of 500 instances running (378 running, 122 starting)
  476 of 500 instances running (476 running, 24 starting)
  499 of 500 instances running (499 running, 1 starting)
  500 of 500 instances running (500 running)
```

**Comment by tlang** [comment]
Thanks Dr. Nic. I think that makes sense also, will prioritize.

**Comment by CardboardMechanic** [comment]
We've been planning to move away from the "X of Y instances running" UX because of some recent improvements that runtime has made. Essentially the first instance starts near-instantly on the current DEA when deploying your app. The idea would be to then encourage users to monitor their instances using `cf instances` instead
