### ISSUE TITLE
cf 5.3.0 gem doesn't pick disk attribute from the manifest file while pushing an app

### ISSUE THREAD

**Issue by ghost** [cloudfoundry-attic/cf#66]
disk attribute is not getting picked up from manifest file while pushing an app. But cf scale <appname> --disk=2G does work properly.

**Comment by ruthie** [comment]
Hi,

Thanks for the bug report.  We're currently moving to version 6 of our cli (which can be found here: http://github.com/cloudfoundry/cli).  Since there's a workaround for this particular issue, it's going to be low priority for us to fix in version 5.  Version 6 doesn't yet support manifests, but that's coming, probably in the next several months.

Best,

@ruthie @charliebevis

**Comment by dajulia3** [comment]
Manifests are now supported in the go CLI http://github.com/cloudfoundry/cli.
Closing this issue
